sudo: required
services:
  - docker
before_install: 
  - docker build -t maitrikpatel2025/react-test -f ./client/Dockerfile.dev .
script:
  - docker run -e CI=true maitrikpatel2025/react-test npm run test -- --coverage
language: generic 

after_success: 
  - docker build -t maitrikpatel2025/multi-client ./client
  - docker build -t maitrikpatel2025/multi-nginx ./nginx
  - docker build -t maitrikpatel2025/multi-server ./server
  - docker build -t maitrikpatel2025/multi-worker ./worker
# log in to the docker login
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take those image and push them to docker hub
  - docker push maitrikpatel2025/multi-client 
  - docker push maitrikpatel2025/multi-nginx 
  - docker push maitrikpatel2025/multi-server 
  - docker push maitrikpatel2025/multi-worker 
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-2"
#   app: "docker-react"
#   env: "dockerreact-env"
#   bucket_name: "elasticbeanstalk-us-east-2-766455893009"
#   bucket_path: "docker-react"
#   on:
#     branch: main
#   access_key_id : $AWS_ACCESS_KEY
#   secret_access_key : "$AWS_SECRET_KEY"